runtime: nodejs

application:
  ports:
    - 3000

persistence:
  size: 2Gi

image:
  repository: theiaide/theia
  tag: 1.4.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # If not set it will use the default
  name:

podSecurityContext:
  runAsUser: 1001
  runAsGroup: 1000
  fsGroup: 1001

service:
  type: ClusterIP
  port: 5050

resources:
  limits:
    cpu: "2"
    memory: 4Gi
