apiVersion: v1
kind: Service
metadata:
  name: {{ include "theia.fullname" . }}
  labels:
    {{- include "theia.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http-theia
    {{- range $port := .Values.application.ports }}
    - port: {{ $port }}
      targetPort: http
      protocol: TCP
      name: http-{{ $port }}
    {{- end }}
  selector:
    {{- include "theia.selectorLabels" . | nindent 4 }}
